### ISSUE TITLE
Failed to resolve entry for package

### ISSUE THREAD

**Issue by KreutzerCode** [NukeJS/laravel-vite-svelte-tailwindcss-starter-template#2]
Hello, I would love to try out a project with Laravel, Svelte and vite, and would be very happy to use this repository to kickstart the application. 

However, after installation, when running `npm run dev`, I get the following message:

`Failed to resolve entry for package "@sveltejs/vite-plugin-svelte".`

My versions in the package.json look like this:

```
    devDependencies": {
        "@rushstack/eslint-patch": "^1.2.0",
        "@sveltejs/vite-plugin-svelte": "^2.0.2",
        "@tailwindcss/forms": "^0.5.3",
        "@tsconfig/svelte": "^3.0.0",
        "@types/node": "^18.13.0",
        "eslint": "^8.33.0",
        "laravel-vite-plugin": "^0.7.4",
        "postcss": "^8.4.21",
        "prettier": "^2.8.4",
        "prettier-plugin-tailwindcss": "^0.2.2",
        "svelte": "^3.55.1",
        "svelte-check": "^3.0.3",
        "tslib": "^2.5.0",
        "typescript": "^4.9.5",
        "vite": "^4.1.1"
    }
```
Is there a problem with the versions or have you noticed this problem before?

Testet on `Laravel 9.2`

**Comment by NukeJS** [comment]
Thanks for creating this issue!
It should be fixed by the PR that I just merged.

To fix it, I just needed to add `type: module` in the `package.json`

**Comment by KreutzerCode** [comment]
Amazing! Thanks for the quick fix, that seems to fix the error mentioned in this Issue. I pulled a fresh copy of the Project and now when starting and calling the frontend with `php artisan serve`, The error message `Failed to load PostCSS config` appears in the frontend.

![grafik](https://user-images.githubusercontent.com/53813841/219873648-3d922f24-d19c-4535-a374-70db81a49bf5.png)

**Comment by NukeJS** [comment]
My bad, I didn't check the artisan serve stuff.

Should be fixed now though with the latest PR.
